In [8]:
import warnings
warnings.filterwarnings("ignore", message="pkg_resources is deprecated")

In [46]:
print(f"*" * 100 + "\n**** Welcome to the Frozen Lake Toy Text Project" + ",a Reinforcement Learning" + "\n**** " + "implementation utilizing Q-Learning,a model-free based approach for solving games")
print(f"****" + " Experimented by:\n**** Bimal Thapa Magar")
print(f"*" * 100)

****************************************************************************************************
**** Welcome to the Frozen Lake Toy Text Project,a Reinforcement Learning
**** implementation utilizing Q-Learning,a model-free based approach for solving games
**** Experimented by:
**** Bimal Thapa Magar
****************************************************************************************************


In [58]:
from pyvirtualdisplay import Display
import numpy as np
import gymnasium as gym
import random
import tqdm
import imageio
import imageio_ffmpeg
from tqdm.notebook import trange

In [57]:
virtual_display =  Display(visible=False,size=(1400,900))
virtual_display.start()

In [59]:
env = gym.make('FrozenLake-v1',desc=None,map_name="4x4",is_slippery=False)

In [100]:
print("___OBSERVATION SPACE______\n")
obs_space = env.observation_space
print("Observation Space:",obs_space.n)
print("Sample Observation:",obs_space.sample())

___OBSERVATION SPACE______

Observation Space: 16
Sample Observation: 11


In [101]:
print("____ACTION SPACE______\n")
act_space = env.action_space
print("Action Space Shape:",act_space.n)
print("Ation Space Sample:",act_space.sample())

____ACTION SPACE______

Action Space Shape: 4
Ation Space Sample: 3


In [102]:
state_space = obs_space.n
print(f"There are total of {state_space} possible states.")
print(f"There are total of {act_space.n} possible actions.")

There are total of 16 possible states.
There are total of 4 possible actions.


In [105]:
# Creating a Q-table of size (state_space,action_space) with initial value of 0 (initializing using numpy array with np.zeros)
def init_q_table(num_states,num_actions):
    q_table = np.zeros((num_states,num_actions))
    return q_table
print("Example Q table looks like this:\n",init_q_table(4,4))

Example Q table looks like this:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
